version: '3'
services:
  apache_principal:
    build: DockerFile2/
    volumes:
      - Apache_data1:/var/www/html/
    ports:
      - "8002:80"
    restart: always
  apache_secundario:
    build: DockerFile3/
    volumes:
      - Apache_data2:/var/www/html/
    ports:
      - "8003:80" 
    restart: always
  varnish:
    depends_on:
      - apache_principal
      - apache_secundario
    build: DockerFile/
    stdin_open: true
    tty: true
    ports:
     - "8006:80"
     - "6082:6082"
    volumes:
      - Varnish_data:/etc/varnish/
    restart: always
volumes:
  Apache_data1:
  Apache_data2:
  Varnish_data:
networks:
 default:
  ipam:
   driver: default
   config:
   - subnet: 172.33.0.0/16
  
