version: '2'
services:
  maestro:
    networks:
      default:
        ipv4_address: 172.40.1.2
    build: DockerFile/
    ports:
      - "3319:3306"
    volumes:
      - mysql_data1:/etc/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: maestro
      MYSQL_DATABASE: maestro
      MYSQL_USER: maestro
      MYSQL_PASSWORD: maestro
  esclavo:
    networks:
      default:
        ipv4_address: 172.40.1.3
    depends_on:
      - maestro
    build: DockerFile2/
    ports:
      - "3318:3306"
    volumes:
      - mysql_data2:/etc/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: esclavo
      MYSQL_DATABASE: maestro
      MYSQL_USER: esclavo
      MYSQL_PASSWORD: esclavo
volumes:
  mysql_data1:
  mysql_data2:
networks:
 default:
  ipam:
   config:
   - subnet: 172.40.0.0/16

