version: '3'
services:
  server1_apache:
    privileged: true
    build: DockerFile2/
    volumes:
      - Apache_router1:/var/www/html/
    ports:
      - "8010:80" 
    restart: always
  router_server:
    privileged: true
    depends_on:
      - server1_apache
    build: DockerFile/
    volumes:
      - Router_data:/etc/
    restart: always
volumes:
  Apache_router1:
  Router_data: 

