version: '3'
services:
  bar:
    build: DockerFile/
    stdin_open: true
    tty: true
    volumes:
      - bar_data:/etc/varnish/
    ports:
      - "8000:80"
      - "6082:6082"
      - "6081:6081"
    restart: always
volumes:
  bar_data:

