CHANGE MASTER TO MASTER_HOST='172.40.1.2',
    MASTER_USER='esclavo', MASTER_PASSWORD='esclavo',
    MASTER_PORT=3306;

GRANT REPLICATION SLAVE ON *.* TO 'esclavo'@'%' IDENTIFIED BY 'esclavo';

START SLAVE;
