version: '3'
services:
  apache_squid:
    networks:
      default:
        ipv4_address: 172.18.0.2
    build: DockerFile2/
    volumes:
      - Apache_dat:/var/www/html/
    ports:
      - "8080:80"
    restart: always
  squid:
    networks:
      default:
        ipv4_address: 172.18.0.3
    build: DockerFile/
    volumes:
      - Squid_data:/etc/squid/
    ports:
      - "3128:3128"
    restart: always
volumes:
  Squid_data:
  Apache_dat:
networks:
 default:
  ipam:
   config:
   - subnet: 172.18.0.0/16
