version: '3'
services:
  squid:
    networks:
      default:
        ipv4_address: 172.10.0.2
    build: DockerFile/
    volumes:
      - Squid_data:/etc/squid/
    ports:
      - "3128:3128"
    restart: always
volumes:
  Squid_data:
networks:
 default:
  ipam:
   config:
   - subnet: 172.10.0.0/16
