version: '3'
services:
  apache_squid:
    build: DockerFile2/
    volumes:
      - Apache_dat:/var/www/html/
    ports:
      - "8080:80"
    restart: always
  squid:
    build: DockerFile/
    volumes:
      - Squid_data:/etc/squid/
    ports:
      - "3128:3128"
    restart: always
volumes:
  Squid_data:
  Apache_dat:
