version: '2'
services:
  maestro:
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    build: DockerFile/
    ports:
      - "3316:3306"
    volumes:
      - db_data1:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: maestro
      MYSQL_DATABASE: maestro
      MYSQL_USER: maestro
      MYSQL_PASSWORD: maestro

  esclavo:
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    depends_on:
      - maestro
    build: DockerFile2/
    ports:
      - "3317:3306"
    volumes:
      - db_data2:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: esclavo
      MYSQL_DATABASE: maestro
      MYSQL_USER: esclavo
      MYSQL_PASSWORD: esclavo

volumes:
  db_data1:
  db_data2:
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24


